[package]
name = "wasm-toys"
version = "0.1.0"
authors = ["Patrick Monaghan <0x5f.manpat@gmail.com>"]
edition = "2018"

[dependencies]
common = { git = "https://github.com/manpat/common-rs.git" }
# common = { path = "../common-rs" }
toy = { git = "https://github.com/manpat/toy-rs.git" }
# toy = { path = "../toy-rs" }
failure = "0.1.1"

[profile.release]
lto = true
